GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Introduction to Next.js 2022",
  "author": "Catalin Pit",
  "url": "http://fake-url2035.com",
  "likes": 106
}
